
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 04 22:00:57 EEST 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 40;
  public static final int GE = 26;
  public static final int UMINUS = 22;
  public static final int LPAREN = 13;
  public static final int CONTINUE = 11;
  public static final int MINUS = 21;
  public static final int RPAREN = 14;
  public static final int BOOLEAN_LITERAL = 41;
  public static final int CHARACTER_LITERAL = 42;
  public static final int SEMICOLON = 15;
  public static final int LT = 23;
  public static final int COMMA = 37;
  public static final int PLUS = 20;
  public static final int IF = 6;
  public static final int DOT = 36;
  public static final int LE = 25;
  public static final int EOF = 0;
  public static final int LNOT = 35;
  public static final int LAND = 33;
  public static final int RETURN = 9;
  public static final int error = 1;
  public static final int LCURLY = 29;
  public static final int LOR = 34;
  public static final int EQEQ = 27;
  public static final int NEQ = 28;
  public static final int BREAK = 10;
  public static final int VOID = 8;
  public static final int EQ = 16;
  public static final int RCURLY = 30;
  public static final int TIMES = 17;
  public static final int LEFT_SQUARE = 32;
  public static final int ELSE = 7;
  public static final int WHILE = 5;
  public static final int MODULUS = 19;
  public static final int RIGHT_SQUARE = 31;
  public static final int DOUBLE_LITERAL = 39;
  public static final int DIVISION = 18;
  public static final int STRUCT = 12;
  public static final int GT = 24;
  public static final int PRINT = 3;
  public static final int DO = 4;
  public static final int INTEGER_LITERAL = 38;
  public static final int IDENTIFIER = 2;
}

