
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 12 00:55:55 EET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 10;
  public static final int LT = 15;
  public static final int SEMICOLON = 8;
  public static final int PLUS = 12;
  public static final int RPAREN = 7;
  public static final int WHILE = 5;
  public static final int DIVISION = 11;
  public static final int RCURLY = 22;
  public static final int IDENTIFIER = 2;
  public static final int LPAREN = 6;
  public static final int GT = 16;
  public static final int LE = 17;
  public static final int STRING_LITERAL = 25;
  public static final int DO = 4;
  public static final int LCURLY = 21;
  public static final int EOF = 0;
  public static final int GE = 18;
  public static final int MINUS = 13;
  public static final int PRINT = 3;
  public static final int error = 1;
  public static final int EQ = 9;
  public static final int INTEGER_LITERAL = 23;
  public static final int EQEQ = 19;
  public static final int NEQ = 20;
  public static final int DOUBLE_LITERAL = 24;
  public static final int UMINUS = 14;
}

